package io.eezo.sbt

/** The stamp `generate` writes into the task's cache directory is `EezoPlugin.witness`, a
  * fingerprint of `RouteGenerator`'s emitted shape; see its own scaladoc for exactly what that
  * fingerprint does and does not cover. What these tests exercise is that the fingerprint really
  * tracks `RouteGenerator.render`, so a change to the emitted shape that forgets to touch anything
  * else still fails a test instead of silently keeping a stale `Routes.scala` for every user whose
  * `app/` directory is untouched. `FileFunction.cached` itself, and whether a live `~compile` loop
  * actually misses the cache when the fingerprint changes, need a real task streams instance and
  * are exercised by hand instead.
  */
class EezoPluginSuite extends munit.FunSuite {

  // Pinned by hand against the template in `RouteGenerator.render`, not by calling into
  // `EezoPlugin.witness` itself: if a future edit changes the preamble, the empty-table arm, a
  // row's shape, the separator between two rows, the filename to verb table, the `_seg` to `:seg`
  // translation or the emit order, this literal stops matching and the test fails, which is the
  // whole point of a fingerprint that no longer depends on a human remembering to bump a version
  // constant. The two rows are listed here in emit order, which is the reverse of the order
  // `witness` hands them to `render`, so a change to `sortRoutes` fails this test too.
  private val expectedWitness =
    "// AUTO-GENERATED by eezo. Do not edit.\n" +
      "package io.eezo.generated\n" +
      "\n" +
      "object Routes {\n" +
      "\n" +
      "  /** Routes written by hand under src/main/scala/app/. */\n" +
      "  private val handwritten: Seq[io.eezo.http.Route] = Seq(\n" +
      "    // no files under src/main/scala/app/\n" +
      "  )\n" +
      "\n" +
      "  val table: io.eezo.http.RouteTable = io.eezo.http.RouteTable(handwritten)\n" +
      "}\n" +
      "// AUTO-GENERATED by eezo. Do not edit.\n" +
      "package io.eezo.generated\n" +
      "\n" +
      "object Routes {\n" +
      "\n" +
      "  /** Routes written by hand under src/main/scala/app/. */\n" +
      "  private val handwritten: Seq[io.eezo.http.Route] = Seq(\n" +
      "    // from src/main/scala/app/eezoWitness/New.scala\n" +
      "    io.eezo.http.Route.Http(\n" +
      "      io.eezo.http.Method.GET,\n" +
      "      io.eezo.http.PathPattern.parse(\"/eezoWitness/new\"),\n" +
      "      req => app.eezoWitness.New.`new`(req)\n" +
      "    ),\n" +
      "    // from src/main/scala/app/eezoWitness/_id/Show.scala\n" +
      "    io.eezo.http.Route.Http(\n" +
      "      io.eezo.http.Method.GET,\n" +
      "      io.eezo.http.PathPattern.parse(\"/eezoWitness/:id\"),\n" +
      "      req => app.eezoWitness._id.Show.show(req)\n" +
      "    )\n" +
      "  )\n" +
      "\n" +
      "  val table: io.eezo.http.RouteTable = io.eezo.http.RouteTable(handwritten)\n" +
      "}\n"

  test("the witness pins RouteGenerator's current emitted shape") {
    assertEquals(EezoPlugin.witness, expectedWitness)
  }

  test("the witness covers the empty-table arm, so render(Seq.empty) alone is not it") {
    assertNotEquals(EezoPlugin.witness, RouteGenerator.render(Seq.empty))
  }
}
