package io.eezo.sbt

/** The stamp `generate` writes into the task's cache directory is `EezoPlugin.witness`, a
  * fingerprint of `RouteGenerator`'s emitted shape; see its own scaladoc for exactly what that
  * fingerprint does and does not cover. What these tests exercise is that the fingerprint really
  * tracks `RouteGenerator.render`, so a change to the emitted shape that forgets to touch anything
  * else still fails a test instead of silently keeping a stale `Routes.scala` for every user whose
  * `app/` directory is untouched. `FileFunction.cached` itself, and whether a live `~compile` loop
  * actually misses the cache when the fingerprint changes, need a real task streams instance and
  * are exercised by hand instead.
  */
class EezoPluginSuite extends munit.FunSuite {

  // Pinned by hand against the template in `RouteGenerator.render`, not by calling into
  // `EezoPlugin.witness` itself: the second half also carries one candidate model, so a change to
  // the derived half of the template, or to the scan that builds a candidate's name, invalidates
  // every project's cache the same way a change to a handwritten row does.
  // if a future edit changes the preamble, the empty-table arm, a
  // row's shape, the separator between two rows, the filename to verb table, the `_seg` to `:seg`
  // translation or the emit order, this literal stops matching and the test fails, which is the
  // whole point of a fingerprint that no longer depends on a human remembering to bump a version
  // constant. The two rows are listed here in emit order, which is the reverse of the order
  // `witness` hands them to `render`, so a change to `sortRoutes` fails this test too.
  private val expectedWitness =
    "// AUTO-GENERATED by eezo. Do not edit.\n" +
      "package io.eezo.generated\n" +
      "\n" +
      "object Routes {\n" +
      "\n" +
      "  /** Routes written by hand under src/main/scala/app/. */\n" +
      "  private val handwritten: Seq[io.eezo.http.Route] = Seq(\n" +
      "    // no files under src/main/scala/app/\n" +
      "  )\n" +
      "\n" +
      "  /** The table this application serves. One line per candidate model below: the compiler,\n" +
      "    * not the generator, decides which of them has a `Resource` and mounts the seven.\n" +
      "    */\n" +
      "  def table(): io.eezo.http.RouteTable = {\n" +
      "    io.eezo.http.RouteTable(handwritten)\n" +
      "  }\n" +
      "}\n" +
      "// AUTO-GENERATED by eezo. Do not edit.\n" +
      "package io.eezo.generated\n" +
      "\n" +
      "object Routes {\n" +
      "\n" +
      "  /** Routes written by hand under src/main/scala/app/. */\n" +
      "  private val handwritten: Seq[io.eezo.http.Route] =\n" +
      "    // from src/main/scala/app/eezoWitness/New.scala\n" +
      "    guardFor[app.eezoWitness.New.type].mounting(\n" +
      "      io.eezo.http.Route.Http(\n" +
      "        io.eezo.http.Method.GET,\n" +
      "        io.eezo.http.PathPattern.parse(\"/eezoWitness/new\"),\n" +
      "        req => app.eezoWitness.New.`new`(req)\n" +
      "      )\n" +
      "    ) ++\n" +
      "    // from src/main/scala/app/eezoWitness/_id/Show.scala\n" +
      "    guardFor[app.eezoWitness._id.Show.type].mounting(\n" +
      "      io.eezo.http.Route.Http(\n" +
      "        io.eezo.http.Method.GET,\n" +
      "        io.eezo.http.PathPattern.parse(\"/eezoWitness/:id\"),\n" +
      "        req => app.eezoWitness._id.Show.show(req)\n" +
      "      )\n" +
      "    )\n" +
      "\n" +
      "  /** The store each derived model gets. Nothing on this application's classpath persists a\n" +
      "    * model, so every one of them lives in memory for as long as the process does.\n" +
      "    */\n" +
      "  private inline def storeFor[A]: io.eezo.core.Store[A] =\n" +
      "    io.eezo.http.InMemoryStore[A]()\n" +
      "\n" +
      "  /** Who may reach this route. A `given Guarded` beside the model or the page is what the\n" +
      "    * table mounts it behind; this application's build declares no eezo-auth, so saying\n" +
      "    * nothing means anyone may reach it.\n" +
      "    */\n" +
      "  private inline def guardFor[A]: io.eezo.http.Guarded[A] =\n" +
      "    scala.compiletime.summonFrom {\n" +
      "      case g: io.eezo.http.Guarded[A] => g\n" +
      "      case _                          => io.eezo.http.Guarded.public[A]\n" +
      "    }\n" +
      "\n" +
      "  /** The table this application serves. One line per candidate model below: the compiler,\n" +
      "    * not the generator, decides which of them has a `Resource` and mounts the seven.\n" +
      "    */\n" +
      "  def table(): io.eezo.http.RouteTable = {\n" +
      "    io.eezo.http.RouteTable(\n" +
      "      (handwritten ++\n" +
      "      // from src/main/scala/eezoWitness/Model.scala\n" +
      "      io.eezo.http.Resource.routesOf[eezoWitness.Model](storeFor[eezoWitness.Model], guardFor[eezoWitness.Model])).distinct\n" +
      "    )\n" +
      "  }\n" +
      "}\n"

  test("the witness pins RouteGenerator's current emitted shape") {
    assertEquals(EezoPlugin.witness(false), expectedWitness)
  }

  test("the witness covers the empty-table arm, so render(Seq.empty) alone is not it") {
    assertNotEquals(
      EezoPlugin.witness(false),
      RouteGenerator.render(Seq.empty, Seq.empty, dbOnClasspath = false)
    )
  }

  test("adding eezo-db to a project changes the witness, so the stale table is regenerated") {
    // The stamp file `generate` writes is `witness`, and it is one of the hashed inputs of the
    // cached generator. Adding `eezo-db` to an existing application touches none of that
    // application's own sources, so if the flag were left out of the fingerprint the cache would
    // hit, `Routes.scala` would keep its in-memory-only `storeFor`, and every model deriving
    // `Table` would silently keep losing its rows at shutdown.
    assertNotEquals(EezoPlugin.witness(true), EezoPlugin.witness(false))
  }

  test("declaring eezo-auth changes the witness too, for the same reason") {
    // Adding the dependency is the whole of the change: no source under `src/main/scala` moves,
    // and the file that has to be regenerated is the one the user cannot edit. Without the flag in
    // the fingerprint the cache hits and the application keeps a table whose `guardFor` still
    // answers silence with `Guarded.public`, so the completeness check the build just asked for is
    // absent from every route until some unrelated source happens to change.
    assertNotEquals(
      EezoPlugin.witness(dbOnClasspath = true, authDeclared = true),
      EezoPlugin.witness(dbOnClasspath = true, authDeclared = false)
    )
    assertNotEquals(
      EezoPlugin.witness(dbOnClasspath = false, authDeclared = true),
      EezoPlugin.witness(dbOnClasspath = false, authDeclared = false)
    )
  }

  test("the witness carries the guard lookup in both readings, so neither can change unseen") {
    // The lookup is emitted whether or not the build declares `eezo-auth`, so the fingerprint has
    // to hold it in both readings. The flag off half is the one that used to hold no guard at all.
    assert(
      clue(EezoPlugin.witness(dbOnClasspath = false, authDeclared = false))
        .contains("private inline def guardFor[A]: io.eezo.http.Guarded[A]")
    )
    assert(
      clue(EezoPlugin.witness(dbOnClasspath = false, authDeclared = true))
        .contains("private inline def guardFor[A](inline name: String)")
    )
  }
}
