package io.eezo.sbt

/** The generator's pure half: the file layout conventions, the emit order, and the text.
  *
  * These are the parts that run before the compiler and hold nothing but text, which is exactly why
  * the warnings this half can raise are textual and the rest wait for boot.
  */
class RouteGeneratorSuite extends munit.FunSuite {

  private def route(relative: String): HandwrittenRoute =
    RouteGenerator.routeFor(relative).getOrElse(fail(s"no route derived from $relative"))

  test("the seven REST filenames map to their method, path and def") {
    assertEquals(route("Index.scala").method, "GET")
    assertEquals(route("Index.scala").path, "/")
    assertEquals(route("widgets/Index.scala").path, "/widgets")
    assertEquals(route("widgets/Index.scala").target, "app.widgets.Index.index")

    assertEquals(route("widgets/New.scala").path, "/widgets/new")
    assertEquals(route("widgets/New.scala").target, "app.widgets.New.`new`")

    assertEquals(route("widgets/_id/Show.scala").path, "/widgets/:id")
    assertEquals(route("widgets/_id/Show.scala").target, "app.widgets._id.Show.show")

    assertEquals(route("widgets/_id/Edit.scala").path, "/widgets/:id/edit")

    assertEquals(route("widgets/Create.scala").method, "POST")
    assertEquals(route("widgets/Create.scala").path, "/widgets")

    assertEquals(route("widgets/_id/Update.scala").method, "PUT")
    assertEquals(route("widgets/_id/Update.scala").path, "/widgets/:id")

    assertEquals(route("widgets/_id/Destroy.scala").method, "DELETE")
    assertEquals(route("widgets/_id/Destroy.scala").path, "/widgets/:id")
  }

  test("a catch-all directory becomes a catch-all segment") {
    assertEquals(route("files/__path/Index.scala").path, "/files/*path")
  }

  test("a custom name is a GET at its own segment, calling a def of the same name") {
    assertEquals(route("Health.scala").method, "GET")
    assertEquals(route("Health.scala").path, "/health")
    assertEquals(route("Health.scala").target, "app.Health.health")
  }

  test("the emitted row remembers the file it came from") {
    assertEquals(route("widgets/New.scala").source, "src/main/scala/app/widgets/New.scala")
  }

  test("a file that is not Scala source contributes no route") {
    assertEquals(RouteGenerator.routeFor("widgets/notes.txt"), None)
  }

  test("emit order puts a literal before a parameter, so /widgets/new is reachable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("widgets/_id/Show.scala"), route("widgets/New.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/widgets/new", "/widgets/:id"))
  }

  test("emit order puts a parameter before a catch-all") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("files/__path/Index.scala"), route("files/_name/Show.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/files/:name", "/files/*path"))
  }

  test("routes with the same shape are ordered by path and then by method, so emission is stable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(
        route("widgets/_id/Update.scala"),
        route("widgets/_id/Destroy.scala"),
        route("widgets/_id/Show.scala")
      )
    )
    assertEquals(sorted.map(_.method), Seq("DELETE", "GET", "PUT"))
  }

  test("the generated file is one object, handwritten first, with a from comment per row") {
    val emitted = RouteGenerator.render(Seq(route("Health.scala")), Seq.empty)
    assert(clue(emitted).startsWith("// AUTO-GENERATED by eezo. Do not edit."))
    assert(clue(emitted).contains("package io.eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Health.scala"))
    assert(clue(emitted).contains("io.eezo.http.PathPattern.parse(\"/health\")"))
    assert(clue(emitted).contains("req => app.Health.health(req)"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test(
    "a fixture laid out like examples/hello/src/main/scala/app/Hello.scala renders the GET /hello row Main.scala's Eezo.run consumes"
  ) {
    val helloRoute = route("Hello.scala")
    assertEquals(helloRoute.method, "GET")
    assertEquals(helloRoute.path, "/hello")
    assertEquals(helloRoute.target, "app.Hello.hello")

    val emitted = RouteGenerator.render(Seq(helloRoute), Seq.empty)
    assert(clue(emitted).contains("package io.eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Hello.scala"))
    assert(clue(emitted).contains("io.eezo.http.Method.GET"))
    assert(clue(emitted).contains("io.eezo.http.PathPattern.parse(\"/hello\")"))
    assert(clue(emitted).contains("req => app.Hello.hello(req)"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test("a file under app missing its expected def warns at generation time") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def show(req: Request) = ??? }"),
      Some(
        "src/main/scala/app/widgets/Index.scala defines no `def index`, so the route GET /widgets will not compile"
      )
    )
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def index(req: Request) = ??? }"),
      None
    )
  }

  test("the def check reads a backticked name as the name it spells") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/New.scala"), "object New { def `new`(req: Request) = ??? }"),
      None
    )
  }

  // ---------------------------------------------------------------- the model scan

  private val widgetSource =
    """package models
      |
      |import io.eezo.core.Id
      |import io.eezo.http.{Form, Resource}
      |
      |case class Widget(id: Id[Widget], name: String) derives Form, Resource
      |""".stripMargin

  test("a top level case class with a derives clause is a candidate, qualified by its package") {
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.scala", widgetSource),
      Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"))
    )
  }

  test("nested package clauses join, so the emitted name is the one the compiler resolves") {
    val source =
      """package com.acme
        |package models
        |
        |case class Widget(id: Long) derives Form
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("Widget.scala", source).map(_.fqn),
      Seq("com.acme.models.Widget")
    )
  }

  test("a case class in the default package is named bare") {
    assertEquals(
      RouteGenerator
        .modelsIn("Widget.scala", "case class Widget(id: Long) derives Form")
        .map(_.fqn),
      Seq("Widget")
    )
  }

  test("a case class with no derives clause is not a candidate") {
    val source =
      """package models
        |
        |case class Page(number: Int)
        |""".stripMargin
    assertEquals(RouteGenerator.modelsIn("models/Page.scala", source), Seq.empty[ModelCandidate])
  }

  test("a derives clause on the next declaration does not make the previous one a candidate") {
    val source =
      """package models
        |
        |case class Page(number: Int)
        |
        |case class Widget(id: Long) derives Form
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("models/Page.scala", source).map(_.fqn),
      Seq("models.Widget")
    )
  }

  test("a derives clause on a multi-line constructor still reaches its case class") {
    val source =
      """package models
        |
        |case class Widget(
        |    id: Long,
        |    name: String
        |) derives Form,
        |      Resource
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.scala", source).map(_.fqn),
      Seq("models.Widget")
    )
  }

  test("a nested case class is not a candidate, because its name is not the one that compiles") {
    val source =
      """package models
        |
        |object Inner {
        |  case class Widget(id: Long) derives Form
        |}
        |""".stripMargin
    assertEquals(RouteGenerator.modelsIn("models/Inner.scala", source), Seq.empty[ModelCandidate])
  }

  test("a file that is not Scala source is scanned for nothing") {
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.txt", widgetSource),
      Seq.empty[ModelCandidate]
    )
  }

  // ---------------------------------------------------------------- the derived half

  test("every candidate gets a routesOf line, and the compiler decides which of them mount") {
    val emitted =
      RouteGenerator.render(
        Seq.empty,
        Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"))
      )
    assert(clue(emitted).contains("// from src/main/scala/models/Widget.scala"))
    assert(clue(emitted).contains("io.eezo.http.Resource.routesOf[models.Widget]("))
    assert(clue(emitted).contains("io.eezo.http.InMemoryStore[models.Widget]()"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test("each candidate mints its own store, because a store is per model and typed by it") {
    val emitted = RouteGenerator.render(
      Seq.empty,
      Seq(
        ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"),
        ModelCandidate("models.Gadget", "src/main/scala/models/Gadget.scala")
      )
    )
    assert(clue(emitted).contains("io.eezo.http.InMemoryStore[models.Widget]()"))
    assert(clue(emitted).contains("io.eezo.http.InMemoryStore[models.Gadget]()"))
    // No shared instance survives: an untyped one is what the bucket parameter existed to index.
    assert(!clue(emitted).contains("val store ="))
  }

  test("with no candidates the table mints no store, so nothing unused is emitted") {
    val emitted = RouteGenerator.render(Seq.empty, Seq.empty)
    assert(!clue(emitted).contains("InMemoryStore"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test(
    "derived rows are emitted after every handwritten one, which is what makes the handwritten win"
  ) {
    val emitted = RouteGenerator.render(
      Seq(route("widgets/Index.scala")),
      Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"))
    )
    assert(
      clue(emitted).indexOf("app.widgets.Index.index") < clue(emitted).indexOf(
        "routesOf[models.Widget]"
      )
    )
  }

  test("candidates are emitted in name order, so two runs produce the same file") {
    val emitted = RouteGenerator.render(
      Seq.empty,
      Seq(
        ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"),
        ModelCandidate("models.Gadget", "src/main/scala/models/Gadget.scala")
      )
    )
    assert(clue(emitted).indexOf("models.Gadget") < clue(emitted).indexOf("models.Widget"))
  }
}
