package io.eezo.sbt

/** The generator's pure half: the file layout conventions, the emit order, and the text.
  *
  * These are the parts that run before the compiler and hold nothing but text, which is exactly why
  * the warnings this half can raise are textual and the rest wait for boot.
  */
class RouteGeneratorSuite extends munit.FunSuite {

  private def route(relative: String): HandwrittenRoute =
    RouteGenerator.routeFor(relative).getOrElse(fail(s"no route derived from $relative"))

  test("the seven REST filenames map to their method, path and def") {
    assertEquals(route("Index.scala").method, "GET")
    assertEquals(route("Index.scala").path, "/")
    assertEquals(route("widgets/Index.scala").path, "/widgets")
    assertEquals(route("widgets/Index.scala").target, "app.widgets.Index.index")

    assertEquals(route("widgets/New.scala").path, "/widgets/new")
    assertEquals(route("widgets/New.scala").target, "app.widgets.New.`new`")

    assertEquals(route("widgets/_id/Show.scala").path, "/widgets/:id")
    assertEquals(route("widgets/_id/Show.scala").target, "app.widgets._id.Show.show")

    assertEquals(route("widgets/_id/Edit.scala").path, "/widgets/:id/edit")

    assertEquals(route("widgets/Create.scala").method, "POST")
    assertEquals(route("widgets/Create.scala").path, "/widgets")

    assertEquals(route("widgets/_id/Update.scala").method, "PUT")
    assertEquals(route("widgets/_id/Update.scala").path, "/widgets/:id")

    assertEquals(route("widgets/_id/Destroy.scala").method, "DELETE")
    assertEquals(route("widgets/_id/Destroy.scala").path, "/widgets/:id")
  }

  test("a catch-all directory becomes a catch-all segment") {
    assertEquals(route("files/__path/Index.scala").path, "/files/*path")
  }

  test("a custom name is a GET at its own segment, calling a def of the same name") {
    assertEquals(route("Health.scala").method, "GET")
    assertEquals(route("Health.scala").path, "/health")
    assertEquals(route("Health.scala").target, "app.Health.health")
  }

  test("the emitted row remembers the file it came from") {
    assertEquals(route("widgets/New.scala").source, "src/main/scala/app/widgets/New.scala")
  }

  test("a file that is not Scala source contributes no route") {
    assertEquals(RouteGenerator.routeFor("widgets/notes.txt"), None)
  }

  test("emit order puts a literal before a parameter, so /widgets/new is reachable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("widgets/_id/Show.scala"), route("widgets/New.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/widgets/new", "/widgets/:id"))
  }

  test("emit order puts a parameter before a catch-all") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("files/__path/Index.scala"), route("files/_name/Show.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/files/:name", "/files/*path"))
  }

  test("routes with the same shape are ordered by path and then by method, so emission is stable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(
        route("widgets/_id/Update.scala"),
        route("widgets/_id/Destroy.scala"),
        route("widgets/_id/Show.scala")
      )
    )
    assertEquals(sorted.map(_.method), Seq("DELETE", "GET", "PUT"))
  }

  test("the generated file is one object, handwritten first, with a from comment per row") {
    val emitted =
      RouteGenerator.render(Seq(route("Health.scala")), Seq.empty, dbOnClasspath = false)
    assert(clue(emitted).startsWith("// AUTO-GENERATED by eezo. Do not edit."))
    assert(clue(emitted).contains("package io.eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Health.scala"))
    assert(clue(emitted).contains("io.eezo.http.PathPattern.parse(\"/health\")"))
    assert(clue(emitted).contains("req => app.Health.health(req)"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test(
    "a fixture laid out like examples/hello/src/main/scala/app/Hello.scala renders the GET /hello row Main.scala's Eezo.run consumes"
  ) {
    val helloRoute = route("Hello.scala")
    assertEquals(helloRoute.method, "GET")
    assertEquals(helloRoute.path, "/hello")
    assertEquals(helloRoute.target, "app.Hello.hello")

    val emitted = RouteGenerator.render(Seq(helloRoute), Seq.empty, dbOnClasspath = false)
    assert(clue(emitted).contains("package io.eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Hello.scala"))
    assert(clue(emitted).contains("io.eezo.http.Method.GET"))
    assert(clue(emitted).contains("io.eezo.http.PathPattern.parse(\"/hello\")"))
    assert(clue(emitted).contains("req => app.Hello.hello(req)"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test("a file under app missing its expected def warns at generation time") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def show(req: Request) = ??? }"),
      Some(
        "src/main/scala/app/widgets/Index.scala defines no `def index`, so the route GET /widgets will not compile"
      )
    )
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def index(req: Request) = ??? }"),
      None
    )
  }

  test("the def check reads a backticked name as the name it spells") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/New.scala"), "object New { def `new`(req: Request) = ??? }"),
      None
    )
  }

  // ---------------------------------------------------------------- the model scan

  private val widgetSource =
    """package models
      |
      |import io.eezo.core.Id
      |import io.eezo.http.{Form, Resource}
      |
      |case class Widget(id: Id[Widget], name: String) derives Form, Resource
      |""".stripMargin

  test("a top level case class with a derives clause is a candidate, qualified by its package") {
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.scala", widgetSource),
      Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"))
    )
  }

  test("nested package clauses join, so the emitted name is the one the compiler resolves") {
    val source =
      """package com.acme
        |package models
        |
        |case class Widget(id: Long) derives Form
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("Widget.scala", source).map(_.fqn),
      Seq("com.acme.models.Widget")
    )
  }

  test("a case class in the default package is named bare") {
    assertEquals(
      RouteGenerator
        .modelsIn("Widget.scala", "case class Widget(id: Long) derives Form")
        .map(_.fqn),
      Seq("Widget")
    )
  }

  test("a case class with no derives clause is not a candidate") {
    val source =
      """package models
        |
        |case class Page(number: Int)
        |""".stripMargin
    assertEquals(RouteGenerator.modelsIn("models/Page.scala", source), Seq.empty[ModelCandidate])
  }

  test("a derives clause on the next declaration does not make the previous one a candidate") {
    val source =
      """package models
        |
        |case class Page(number: Int)
        |
        |case class Widget(id: Long) derives Form
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("models/Page.scala", source).map(_.fqn),
      Seq("models.Widget")
    )
  }

  test("a derives clause on a multi-line constructor still reaches its case class") {
    val source =
      """package models
        |
        |case class Widget(
        |    id: Long,
        |    name: String
        |) derives Form,
        |      Resource
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.scala", source).map(_.fqn),
      Seq("models.Widget")
    )
  }

  test("a case class nested in objects is a candidate, named through the enclosing path") {
    val source =
      """package models
        |
        |object Inner {
        |  case class Widget(id: Long) derives Form
        |}
        |""".stripMargin
    assertEquals(
      RouteGenerator.modelsIn("models/Inner.scala", source).map(_.fqn),
      Seq("models.Inner.Widget")
    )
  }

  test("a file that is not Scala source is scanned for nothing") {
    assertEquals(
      RouteGenerator.modelsIn("models/Widget.txt", widgetSource),
      Seq.empty[ModelCandidate]
    )
  }

  // ---------------------------------------------------------------- the derived half

  test("every candidate gets a routesOf line, and the compiler decides which of them mount") {
    val emitted =
      RouteGenerator.render(
        Seq.empty,
        Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala")),
        dbOnClasspath = false
      )
    assert(clue(emitted).contains("// from src/main/scala/models/Widget.scala"))
    assert(
      clue(emitted).contains(
        "io.eezo.http.Resource.routesOf[models.Widget](storeFor[models.Widget], " +
          "guardFor[models.Widget])"
      )
    )
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test("each candidate mints its own store, because a store is per model and typed by it") {
    val emitted = RouteGenerator.render(
      Seq.empty,
      Seq(
        ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"),
        ModelCandidate("models.Gadget", "src/main/scala/models/Gadget.scala")
      ),
      dbOnClasspath = false
    )
    assert(clue(emitted).contains("storeFor[models.Widget]"))
    assert(clue(emitted).contains("storeFor[models.Gadget]"))
    // No shared instance survives: an untyped one is what the bucket parameter existed to index.
    assert(!clue(emitted).contains("val store ="))
  }

  test("with no candidates the table mints no store, so nothing unused is emitted") {
    val emitted = RouteGenerator.render(Seq.empty, Seq.empty, dbOnClasspath = false)
    assert(!clue(emitted).contains("InMemoryStore"))
    assert(clue(emitted).contains("def table(): io.eezo.http.RouteTable"))
  }

  test(
    "derived rows are emitted after every handwritten one, which is what makes the handwritten win"
  ) {
    val emitted = RouteGenerator.render(
      Seq(route("widgets/Index.scala")),
      Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala")),
      dbOnClasspath = false
    )
    assert(
      clue(emitted).indexOf("app.widgets.Index.index") < clue(emitted).indexOf(
        "routesOf[models.Widget]"
      )
    )
  }

  test("candidates are emitted in name order, so two runs produce the same file") {
    val emitted = RouteGenerator.render(
      Seq.empty,
      Seq(
        ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"),
        ModelCandidate("models.Gadget", "src/main/scala/models/Gadget.scala")
      ),
      dbOnClasspath = false
    )
    assert(clue(emitted).indexOf("models.Gadget") < clue(emitted).indexOf("models.Widget"))
  }

  // ------------------------------------------------------- which store the derived rows get

  private val widget = Seq(ModelCandidate("models.Widget", "src/main/scala/models/Widget.scala"))

  test("with no database on the classpath every model's store is the in-memory one") {
    val emitted = RouteGenerator.render(Seq.empty, widget, dbOnClasspath = false)
    assert(clue(emitted).contains("private inline def storeFor[A]: io.eezo.core.Store[A] ="))
    assert(clue(emitted).contains("io.eezo.http.InMemoryStore[A]()"))
    assert(clue(emitted).contains("storeFor[models.Widget]"))
    // Not one mention of db anywhere. `io.eezo.db.Table` does not resolve in an application that
    // has no database on its classpath, so a branch naming it would fail that application's own
    // compile, which is the whole reason the flag exists.
    assert(!clue(emitted).contains("io.eezo.db"))
    // The whole body, asserted rather than the file, because the guard lookup beside it summons
    // for its own reasons. Two arms even with no database, because ownership is `http`'s and
    // resolves wherever a route is mounted at all.
    assert(
      clue(emitted).contains(
        "  private inline def storeFor[A]: io.eezo.core.Store[A] =\n" +
          "    scala.compiletime.summonFrom {\n" +
          "      case o: io.eezo.http.Owned[A, ?] => io.eezo.http.InMemoryStore.scoped(o.ownerOf)\n" +
          "      case _                           => io.eezo.http.InMemoryStore[A]()\n" +
          "    }"
      )
    )
  }

  test("an owned model cannot land on an unscoped store, because its arm comes first") {
    Seq(true, false).foreach { withDb =>
      val emitted = RouteGenerator.render(Seq.empty, widget, dbOnClasspath = withDb)
      val owned   = clue(emitted).indexOf("case o: io.eezo.http.Owned[A, ?]")
      assert(owned >= 0, emitted)
      // Every other arm of the lookup is behind it, so a model that declared ownership is scoped
      // before anything has the chance to hand it the whole table.
      assert(owned < clue(emitted).indexOf("case _"), emitted)
      if (withDb) assert(owned < clue(emitted).indexOf("case t: io.eezo.db.Table[A]"), emitted)
    }
  }

  test("an owned model with a Table is scoped through db's own owner aware half") {
    val emitted = RouteGenerator.render(Seq.empty, widget, dbOnClasspath = true)
    assert(clue(emitted).contains("io.eezo.db.JdbcStore.owned(o.ownerOf)(using t, summon)"))
    assert(clue(emitted).contains("io.eezo.http.Scoped("))
    // An owned model with no `Table` is scoped in memory, the same per-model decision the
    // unscoped arm below it makes.
    assert(clue(emitted).contains("case _ => io.eezo.http.InMemoryStore.scoped(o.ownerOf)"))
  }

  test("with eezo-db on the classpath the compiler picks per model, off the model's Table") {
    val emitted = RouteGenerator.render(Seq.empty, widget, dbOnClasspath = true)
    assert(clue(emitted).contains("private inline def storeFor[A]: io.eezo.core.Store[A] ="))
    assert(clue(emitted).contains("scala.compiletime.summonFrom {"))
    assert(
      clue(emitted).contains("case t: io.eezo.db.Table[A] => io.eezo.db.JdbcStore[A]()(using t)")
    )
    // The fallback stays, because a database on the classpath says nothing about whether any one
    // model derives `Table`.
    assert(clue(emitted).contains("io.eezo.http.InMemoryStore[A]()"))
    assert(clue(emitted).contains("storeFor[models.Widget]"))
  }

  test("neither arm imports io.eezo.db, because an unused import fails a -Werror build") {
    assert(
      !clue(RouteGenerator.render(Seq.empty, widget, dbOnClasspath = true))
        .contains("import io.eezo.db")
    )
    assert(
      !clue(RouteGenerator.render(Seq.empty, widget, dbOnClasspath = false))
        .contains("import io.eezo.db")
    )
  }

  // ------------------------------------------------------- which routes have to say who may reach them

  private val helloRouteAndModel = (Seq(route("widgets/Index.scala")), widget)

  test("every mounted route goes through the lookup, whether or not the build declares auth") {
    // The defect this covers: the lookup used to be emitted only where the build named
    // `eezo-auth`, so an application on the umbrella, or one reaching auth through a `dependsOn`
    // module, mounted every route bare and read nobody's `given Guarded`. `Guarded` lives in
    // `http`, so the lookup resolves wherever a route is mounted at all and is emitted always.
    val (routes, models) = helloRouteAndModel

    val lenient = RouteGenerator.render(routes, models, dbOnClasspath = true, authDeclared = false)
    assert(clue(lenient).contains("guardFor[app.widgets.Index.type].mounting("))
    assert(
      clue(lenient).contains(
        "io.eezo.http.Resource.routesOf[models.Widget](storeFor[models.Widget], " +
          "guardFor[models.Widget])"
      )
    )

    val strict = RouteGenerator.render(routes, models, dbOnClasspath = true, authDeclared = true)
    assert(
      clue(strict).contains("""guardFor[app.widgets.Index.type]("app.widgets.Index").mounting(""")
    )
    assert(
      clue(strict).contains(
        """io.eezo.http.Resource.routesOf[models.Widget](storeFor[models.Widget], """ +
          """guardForModel[models.Widget]("models.Widget"))"""
      )
    )
  }

  test("silence is public where the build declares no auth, and an error where it declares it") {
    val (routes, models) = helloRouteAndModel

    val lenient = RouteGenerator.render(routes, models, dbOnClasspath = false, authDeclared = false)
    assert(clue(lenient).contains("private inline def guardFor[A]: io.eezo.http.Guarded[A] ="))
    assert(clue(lenient).contains("case g: io.eezo.http.Guarded[A] => g"))
    assert(clue(lenient).contains("=> io.eezo.http.Guarded.public[A]"))
    assert(!clue(lenient).contains("scala.compiletime.error("))
    // No name reaches the lenient helper, because it has no error to name anything in, and a
    // parameter its body never reads is the `unused explicit parameter` that `-Wunused:all`
    // reports in the application's own build.
    assert(!clue(lenient).contains("\"app.widgets.Index\""))
    // Nor a second helper: with no error to spare a model from, `guardForModel` would be a second
    // spelling of the one above it.
    assert(!clue(lenient).contains("guardForModel"))

    val strict = RouteGenerator.render(routes, models, dbOnClasspath = false, authDeclared = true)
    assert(clue(strict).contains("private inline def guardFor[A](inline name: String)"))
    assert(clue(strict).contains("scala.compiletime.error("))
    // A model with a `derives` clause but no `Resource`, such as the blog's `User`, mounts nothing
    // and must not be asked to declare anything.
    assert(clue(strict).contains("private inline def guardForModel[A](inline name: String)"))
    assert(clue(strict).contains("case _: io.eezo.http.Resource[A] => guardFor[A](name)"))
    assert(clue(strict).contains("=> io.eezo.http.Guarded.public[A]"))
  }

  test("the table takes distinct in both readings, because a guard carries its own pages") {
    // A guard's login and logout routes travel inside every declaration it made, so a table with
    // two guarded things holds them twice and `RouteTable` refuses to boot. The declaration can
    // now exist in an application whose build never named `eezo-auth`, so the line cannot be tied
    // to the flag any more.
    val (routes, models) = helloRouteAndModel
    assert(
      clue(RouteGenerator.render(routes, models, dbOnClasspath = true, authDeclared = false))
        .contains(").distinct")
    )
    assert(
      clue(RouteGenerator.render(routes, Seq.empty, dbOnClasspath = true, authDeclared = false))
        .contains("io.eezo.http.RouteTable(handwritten.distinct, identify)")
    )
  }

  test("the table is handed the stamp its own declarations compose, in both readings") {
    // The table names the current user on a socket upgrade, and what it names with is composed out
    // of the very declarations the rows were mounted behind. Composed rather than looked up again,
    // so there is no second place a route could be mounted behind one declaration and named by
    // another.
    val (routes, models) = helloRouteAndModel

    val lenient = RouteGenerator.render(routes, models, dbOnClasspath = true, authDeclared = false)
    assert(
      clue(lenient).contains(
        "private val identify: io.eezo.http.Request => io.eezo.http.Request ="
      )
    )
    assert(clue(lenient).contains("guardFor[app.widgets.Index.type].identify"))
    assert(clue(lenient).contains("guardFor[models.Widget].identify"))
    assert(clue(lenient).contains(").distinct,\n      identify\n    )"))

    val strict = RouteGenerator.render(routes, models, dbOnClasspath = true, authDeclared = true)
    assert(
      clue(strict).contains("""guardFor[app.widgets.Index.type]("app.widgets.Index").identify""")
    )
    assert(clue(strict).contains("""guardForModel[models.Widget]("models.Widget").identify"""))
  }

  test("a table of handwritten rows alone is named by them too") {
    val routesOnly =
      RouteGenerator.render(Seq(route("widgets/Index.scala")), Seq.empty, dbOnClasspath = false)
    assert(clue(routesOnly).contains("io.eezo.http.RouteTable(handwritten.distinct, identify)"))
  }

  test("the guard helpers follow the rows that call them, like storeFor does") {
    // No handwritten routes and no models: nothing calls either helper, and an uncalled
    // `private inline def` is a `-Wunused:all` failure in the application's own build. Nothing is
    // taken `distinct` either, because there is no row to hold twice.
    Seq(true, false).foreach { declared =>
      val bare =
        RouteGenerator.render(Seq.empty, Seq.empty, dbOnClasspath = false, authDeclared = declared)
      assert(!clue(bare).contains("guardFor"))
      // Nothing was mounted, so there is no declaration to name anyone with, and a `private val`
      // holding a composition of nothing is one more thing `-Wunused:all` would report.
      assert(!clue(bare).contains("identify"))
      assert(clue(bare).contains("io.eezo.http.RouteTable(handwritten)"))
    }

    // Handwritten routes but no models: the route helper is called, the model one is not.
    val routesOnly = RouteGenerator.render(
      Seq(route("widgets/Index.scala")),
      Seq.empty,
      dbOnClasspath = false,
      authDeclared = true
    )
    assert(clue(routesOnly).contains("def guardFor[A]"))
    assert(!clue(routesOnly).contains("def guardForModel[A]"))
  }

  // ------------------------------------------------------- the helpers a compiler sees for real

  /** Where the one compiled copy of the emitted guard helpers lives.
    *
    * ADR 0002 cross builds this plugin for sbt 1 on Scala 2.12, so no Scala 3 module can depend on
    * it and compile what `render` returns. `modules/eezo`'s `GeneratedGuardForSuite` therefore
    * holds a copy and compiles that, which is a drift waiting to happen. Reading the file here and
    * demanding the emitted text verbatim is the whole pin: a helper that changes without its copy
    * changing is a failure in this suite, on both axes, with no shared artifact to publish.
    */
  private val compiledCopy = "modules/eezo/src/test/scala/io/eezo/GeneratedGuardForSuite.scala"

  /** The file, found from the working directory sbt runs a suite in and from its parents, so that
    * this passes whether the suite was started at the build root or inside the module.
    */
  private def sourceOf(path: String): String = {
    def upwards(from: java.io.File, left: Int): Option[java.io.File] = {
      val candidate = new java.io.File(from, path)
      if (candidate.isFile) Some(candidate)
      else if (left == 0 || from.getParentFile == null) None
      else upwards(from.getParentFile, left - 1)
    }
    val here   = new java.io.File(".").getCanonicalFile
    val found  = upwards(here, 4).getOrElse(fail(s"$path not found from $here"))
    val source = scala.io.Source.fromFile(found, "UTF-8")
    try source.mkString
    finally source.close()
  }

  test("the helpers GeneratedGuardForSuite compiles are the ones the generator emits") {
    // The store lookup is pinned here for the reason the guard lookup is, and for one more: its
    // owned arm has to resolve `Column[Id[U]]` without naming `U`, and only a compiler can say
    // whether it does.
    val compiled = sourceOf(compiledCopy)
    Seq(
      RouteGenerator.guardFor(authDeclared = true),
      RouteGenerator.guardFor(authDeclared = false),
      RouteGenerator.guardForModel,
      RouteGenerator.identifying,
      RouteGenerator.storeFor(dbOnClasspath = true),
      RouteGenerator.storeFor(dbOnClasspath = false)
    ).foreach { helper =>
      assert(
        compiled.contains(helper),
        s"$compiledCopy no longer holds this helper verbatim:\n$helper"
      )
    }
  }

  test("with no candidates neither arm emits storeFor, because nothing would call it") {
    // A `private inline def` nobody calls is a `-Wunused:all` failure in any application that
    // compiles with `-Werror`, so the helper is tied to the derived rows that use it.
    assert(
      !clue(RouteGenerator.render(Seq.empty, Seq.empty, dbOnClasspath = false)).contains("storeFor")
    )
    assert(
      !clue(RouteGenerator.render(Seq.empty, Seq.empty, dbOnClasspath = true)).contains("storeFor")
    )
  }
}
