package eezo.sbt

/** The generator's pure half: the file layout conventions, the emit order, and the text.
  *
  * These are the parts that run before the compiler and hold nothing but text, which is exactly why
  * the warnings this half can raise are textual and the rest wait for boot.
  */
class RouteGeneratorSuite extends munit.FunSuite {

  private def route(relative: String): HandwrittenRoute =
    RouteGenerator.routeFor(relative).getOrElse(fail(s"no route derived from $relative"))

  test("the seven REST filenames map to their method, path and def") {
    assertEquals(route("Index.scala").method, "GET")
    assertEquals(route("Index.scala").path, "/")
    assertEquals(route("widgets/Index.scala").path, "/widgets")
    assertEquals(route("widgets/Index.scala").target, "app.widgets.Index.index")

    assertEquals(route("widgets/New.scala").path, "/widgets/new")
    assertEquals(route("widgets/New.scala").target, "app.widgets.New.`new`")

    assertEquals(route("widgets/_id/Show.scala").path, "/widgets/:id")
    assertEquals(route("widgets/_id/Show.scala").target, "app.widgets._id.Show.show")

    assertEquals(route("widgets/_id/Edit.scala").path, "/widgets/:id/edit")

    assertEquals(route("widgets/Create.scala").method, "POST")
    assertEquals(route("widgets/Create.scala").path, "/widgets")

    assertEquals(route("widgets/_id/Update.scala").method, "PUT")
    assertEquals(route("widgets/_id/Update.scala").path, "/widgets/:id")

    assertEquals(route("widgets/_id/Destroy.scala").method, "DELETE")
    assertEquals(route("widgets/_id/Destroy.scala").path, "/widgets/:id")
  }

  test("a catch-all directory becomes a catch-all segment") {
    assertEquals(route("files/__path/Index.scala").path, "/files/*path")
  }

  test("a custom name is a GET at its own segment, calling a def of the same name") {
    assertEquals(route("Health.scala").method, "GET")
    assertEquals(route("Health.scala").path, "/health")
    assertEquals(route("Health.scala").target, "app.Health.health")
  }

  test("the emitted row remembers the file it came from") {
    assertEquals(route("widgets/New.scala").source, "src/main/scala/app/widgets/New.scala")
  }

  test("a file that is not Scala source contributes no route") {
    assertEquals(RouteGenerator.routeFor("widgets/notes.txt"), None)
  }

  test("emit order puts a literal before a parameter, so /widgets/new is reachable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("widgets/_id/Show.scala"), route("widgets/New.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/widgets/new", "/widgets/:id"))
  }

  test("emit order puts a parameter before a catch-all") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(route("files/__path/Index.scala"), route("files/_name/Show.scala"))
    )
    assertEquals(sorted.map(_.path), Seq("/files/:name", "/files/*path"))
  }

  test("routes with the same shape are ordered by path and then by method, so emission is stable") {
    val sorted = RouteGenerator.sortRoutes(
      Seq(
        route("widgets/_id/Update.scala"),
        route("widgets/_id/Destroy.scala"),
        route("widgets/_id/Show.scala")
      )
    )
    assertEquals(sorted.map(_.method), Seq("DELETE", "GET", "PUT"))
  }

  test("the generated file is one object, handwritten first, with a from comment per row") {
    val emitted = RouteGenerator.render(Seq(route("Health.scala")))
    assert(clue(emitted).startsWith("// AUTO-GENERATED by eezo. Do not edit."))
    assert(clue(emitted).contains("package eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Health.scala"))
    assert(clue(emitted).contains("eezo.http.PathPattern.parse(\"/health\")"))
    assert(clue(emitted).contains("req => app.Health.health(req)"))
    assert(clue(emitted).contains("val table: eezo.http.RouteTable"))
  }

  test(
    "a fixture laid out like examples/hello/src/main/scala/app/Hello.scala renders the GET /hello row Main.scala's Eezo.run consumes"
  ) {
    val helloRoute = route("Hello.scala")
    assertEquals(helloRoute.method, "GET")
    assertEquals(helloRoute.path, "/hello")
    assertEquals(helloRoute.target, "app.Hello.hello")

    val emitted = RouteGenerator.render(Seq(helloRoute))
    assert(clue(emitted).contains("package eezo.generated"))
    assert(clue(emitted).contains("object Routes"))
    assert(clue(emitted).contains("// from src/main/scala/app/Hello.scala"))
    assert(clue(emitted).contains("eezo.http.Method.GET"))
    assert(clue(emitted).contains("eezo.http.PathPattern.parse(\"/hello\")"))
    assert(clue(emitted).contains("req => app.Hello.hello(req)"))
    assert(clue(emitted).contains("val table: eezo.http.RouteTable"))
  }

  test("a file under app missing its expected def warns at generation time") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def show(req: Request) = ??? }"),
      Some(
        "src/main/scala/app/widgets/Index.scala defines no `def index`, so the route GET /widgets will not compile"
      )
    )
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/Index.scala"), "object Index { def index(req: Request) = ??? }"),
      None
    )
  }

  test("the def check reads a backticked name as the name it spells") {
    assertEquals(
      RouteGenerator
        .missingDef(route("widgets/New.scala"), "object New { def `new`(req: Request) = ??? }"),
      None
    )
  }
}
