package io.eezo.sbt

/** The deployment container, rendered. Pure strings, so the shape is testable without Docker and
  * identical on both sbt axes.
  *
  * The image holds exactly what production needs: a JRE, the staged jars, and the committed
  * migrations under `db/` — no sbt, no build tooling. `WORKDIR /app` is load-bearing: the migration
  * runtime resolves `db/` against the working directory, so the `COPY db db` below is what makes
  * `migrate --apply` on the platform find the same migration files `freeze` wrote locally. An image
  * without them would report "no pending migrations" against an empty database, which is the
  * failure this comment exists to prevent.
  *
  * `ENTRYPOINT`, not `CMD`: Fly's `release_command` replaces the CMD and keeps the entrypoint, so
  * `release_command = "migrate --apply"` becomes arguments to the application's own `main` — the
  * same dispatch every other CLI command goes through. No arguments means `boot`, which serves.
  */
private[sbt] object Deploy {

  def dockerfile(mainClass: String, javaVersion: String): String =
    s"""# Generated by eezo (eezoStage). Regenerated on every stage; do not edit.
       |FROM eclipse-temurin:$javaVersion-jre-noble
       |WORKDIR /app
       |COPY lib lib
       |COPY db db
       |# MaxRAMPercentage over a fixed -Xmx, because the platform decides the machine size.
       |ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-cp", "lib/*", "$mainClass"]
       |""".stripMargin
}
